"""initial procurement schema

Revision ID: 27f45e7c21d7
Revises:
Create Date: 2026-09-02 20:50:02.548443
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base_class

revision: str = "27f45e7c21d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("taxonomy", sa.String(length=60), nullable=False),
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name="uq_categories_slug"),
    )
    op.create_index(op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(
        "ix_categories_parent_id_name", "categories", ["parent_id", "name"], unique=False
    )

    op.create_table(
        "contacts",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("role", sa.String(length=160), nullable=True),
        sa.Column("organization", sa.String(length=240), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("fax", sa.String(length=64), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("fingerprint", name="uq_contacts_fingerprint"),
    )
    op.create_index(op.f("ix_contacts_created_at"), "contacts", ["created_at"], unique=False)
    op.create_index("ix_contacts_email", "contacts", ["email"], unique=False)

    op.create_table(
        "provinces",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("official_website", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provinces")),
        sa.UniqueConstraint("code", name="uq_provinces_code"),
    )
    op.create_index(op.f("ix_provinces_created_at"), "provinces", ["created_at"], unique=False)
    op.create_index(op.f("ix_provinces_name"), "provinces", ["name"], unique=True)
    op.create_index(op.f("ix_provinces_slug"), "provinces", ["slug"], unique=True)

    op.create_table(
        "source_connectors",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("connector_type", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "config_schema",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("requires_browser", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_connectors")),
    )
    op.create_index(
        op.f("ix_source_connectors_created_at"), "source_connectors", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_source_connectors_key"), "source_connectors", ["key"], unique=True)

    op.create_table(
        "districts",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("province_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("official_website", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_districts_province_id_provinces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
        sa.UniqueConstraint("code", name="uq_districts_code"),
    )
    op.create_index(op.f("ix_districts_created_at"), "districts", ["created_at"], unique=False)
    op.create_index(op.f("ix_districts_name"), "districts", ["name"], unique=False)
    op.create_index(op.f("ix_districts_province_id"), "districts", ["province_id"], unique=False)
    op.create_index(
        "ix_districts_province_id_name", "districts", ["province_id", "name"], unique=False
    )
    op.create_index(op.f("ix_districts_slug"), "districts", ["slug"], unique=True)

    op.create_table(
        "municipalities",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("province_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("district_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("official_website", sa.Text(), nullable=True),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("data_source", sa.String(length=120), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
            name=op.f("fk_municipalities_district_id_districts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_municipalities_province_id_provinces"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipalities")),
        sa.UniqueConstraint("code", name="uq_municipalities_code"),
    )
    op.create_index(
        op.f("ix_municipalities_created_at"), "municipalities", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_municipalities_district_id"), "municipalities", ["district_id"], unique=False
    )
    op.create_index(op.f("ix_municipalities_name"), "municipalities", ["name"], unique=False)
    op.create_index("ix_municipalities_name_lower", "municipalities", ["name"], unique=False)
    op.create_index(
        op.f("ix_municipalities_province_id"), "municipalities", ["province_id"], unique=False
    )
    op.create_index(
        "ix_municipalities_province_id_type",
        "municipalities",
        ["province_id", "type"],
        unique=False,
    )
    op.create_index(op.f("ix_municipalities_slug"), "municipalities", ["slug"], unique=True)

    op.create_table(
        "municipality_sources",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("organization", sa.String(length=240), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("procurement_scope", sa.String(length=24), nullable=False),
        sa.Column("municipality_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("province_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("connector_type", sa.String(length=32), nullable=False),
        sa.Column("connector_key", sa.String(length=80), nullable=True),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("crawl_frequency_minutes", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("average_response_time_ms", sa.Float(), nullable=True),
        sa.Column("last_http_status", sa.Integer(), nullable=True),
        sa.Column("health_status", sa.String(length=16), nullable=False),
        sa.Column("robots_policy", sa.String(length=16), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "crawl_frequency_minutes >= 5", name=op.f("ck_municipality_sources_crawl_frequency_min")
        ),
        sa.CheckConstraint(
            "priority >= 0 AND priority <= 1000",
            name=op.f("ck_municipality_sources_priority_range"),
        ),
        sa.CheckConstraint(
            "rate_limit_per_minute > 0", name=op.f("ck_municipality_sources_rate_limit_positive")
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipalities.id"],
            name=op.f("fk_municipality_sources_municipality_id_municipalities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_municipality_sources_province_id_provinces"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipality_sources")),
        sa.UniqueConstraint("slug", name="uq_municipality_sources_slug"),
    )
    op.create_index(
        op.f("ix_municipality_sources_active"), "municipality_sources", ["active"], unique=False
    )
    op.create_index(
        "ix_municipality_sources_active_priority",
        "municipality_sources",
        ["active", "priority"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipality_sources_created_at"),
        "municipality_sources",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_municipality_sources_health_status",
        "municipality_sources",
        ["health_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipality_sources_municipality_id"),
        "municipality_sources",
        ["municipality_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipality_sources_name"), "municipality_sources", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_municipality_sources_province_id"),
        "municipality_sources",
        ["province_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_municipality_sources_source_type"),
        "municipality_sources",
        ["source_type"],
        unique=False,
    )

    op.create_table(
        "ingestion_jobs",
        sa.Column("source_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("job_type", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("items_found", sa.Integer(), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("items_skipped", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("queue_job_id", sa.String(length=120), nullable=True),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_ingestion_jobs_attempt_non_negative")),
        sa.CheckConstraint(
            "max_attempts >= 1", name=op.f("ck_ingestion_jobs_max_attempts_positive")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["municipality_sources.id"],
            name=op.f("fk_ingestion_jobs_source_id_municipality_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_created_at"), "ingestion_jobs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_queue_job_id"), "ingestion_jobs", ["queue_job_id"], unique=False
    )
    op.create_index(
        "ix_ingestion_jobs_source_id_created_at",
        "ingestion_jobs",
        ["source_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_status_scheduled_for",
        "ingestion_jobs",
        ["status", "scheduled_for"],
        unique=False,
    )

    op.create_table(
        "procurement_opportunities",
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("reference_number", sa.String(length=200), nullable=True),
        sa.Column("reference_number_normalized", sa.String(length=200), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("procurement_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("organization", sa.String(length=240), nullable=True),
        sa.Column("municipality_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("province_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("source_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_timezone", sa.String(length=64), nullable=True),
        sa.Column(
            "raw_dates",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("submission_method", sa.String(length=120), nullable=True),
        sa.Column("submission_url", sa.Text(), nullable=True),
        sa.Column("submission_address", sa.Text(), nullable=True),
        sa.Column("briefing_required", sa.Boolean(), nullable=True),
        sa.Column("briefing_compulsory", sa.Boolean(), nullable=True),
        sa.Column("briefing_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("briefing_location", sa.Text(), nullable=True),
        sa.Column("contact_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("raw_payload_key", sa.String(length=300), nullable=True),
        sa.Column(
            "parser_metadata",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("data_quality", sa.String(length=16), nullable=False),
        sa.Column(
            "quality_issues",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_test_fixture", sa.Boolean(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_value IS NULL OR estimated_value >= 0",
            name=op.f("ck_procurement_opportunities_estimated_value_non_negative"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_procurement_opportunities_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_procurement_opportunities_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["municipality_id"],
            ["municipalities.id"],
            name=op.f("fk_procurement_opportunities_municipality_id_municipalities"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["province_id"],
            ["provinces.id"],
            name=op.f("fk_procurement_opportunities_province_id_provinces"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["municipality_sources.id"],
            name=op.f("fk_procurement_opportunities_source_id_municipality_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_procurement_opportunities")),
        sa.UniqueConstraint("fingerprint", name="uq_opportunity_fingerprint"),
        sa.UniqueConstraint(
            "municipality_id", "reference_number", name="uq_opportunity_municipality_reference"
        ),
        sa.UniqueConstraint("source_id", "external_id", name="uq_opportunity_source_external"),
    )
    op.create_index(
        "ix_opportunities_content_hash", "procurement_opportunities", ["content_hash"], unique=False
    )
    op.create_index(
        "ix_opportunities_municipality_status",
        "procurement_opportunities",
        ["municipality_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_procurement_type",
        "procurement_opportunities",
        ["procurement_type"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_province_status",
        "procurement_opportunities",
        ["province_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_published_at", "procurement_opportunities", ["published_at"], unique=False
    )
    op.create_index(
        "ix_opportunities_source_last_seen",
        "procurement_opportunities",
        ["source_id", "last_seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_status_closing_at",
        "procurement_opportunities",
        ["status", "closing_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_opportunities_created_at"),
        "procurement_opportunities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_opportunities_reference_number"),
        "procurement_opportunities",
        ["reference_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_opportunities_status"),
        "procurement_opportunities",
        ["status"],
        unique=False,
    )

    op.create_table(
        "documents",
        sa.Column("opportunity_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("document_type", sa.String(length=32), nullable=False),
        sa.Column("document_format", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.String(length=400), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("storage_key", sa.String(length=400), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("download_error", sa.Text(), nullable=True),
        sa.Column("is_downloaded", sa.Boolean(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_size IS NULL OR file_size >= 0", name=op.f("ck_documents_file_size_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["procurement_opportunities.id"],
            name=op.f("fk_documents_opportunity_id_procurement_opportunities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("opportunity_id", "source_url", name="uq_documents_opportunity_url"),
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(
        "ix_documents_opportunity_id_created",
        "documents",
        ["opportunity_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_documents_sha256", "documents", ["sha256"], unique=False)

    op.create_table(
        "opportunity_categories",
        sa.Column("opportunity_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("category_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("assigned_by", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_opportunity_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["procurement_opportunities.id"],
            name=op.f("fk_opportunity_categories_opportunity_id_procurement_opportunities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "category_id", name=op.f("pk_opportunity_categories")
        ),
    )
    op.create_index(
        "ix_opportunity_categories_category_id",
        "opportunity_categories",
        ["category_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_categories_created_at"),
        "opportunity_categories",
        ["created_at"],
        unique=False,
    )

    op.create_table(
        "source_runs",
        sa.Column("source_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("job_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("items_found", sa.Integer(), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("items_skipped", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("documents_found", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "items_found >= 0", name=op.f("ck_source_runs_items_found_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_source_runs_job_id_ingestion_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["municipality_sources.id"],
            name=op.f("fk_source_runs_source_id_municipality_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_runs")),
    )
    op.create_index(op.f("ix_source_runs_created_at"), "source_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_source_runs_job_id"), "source_runs", ["job_id"], unique=False)
    op.create_index(
        "ix_source_runs_source_id_started_at",
        "source_runs",
        ["source_id", "started_at"],
        unique=False,
    )

    op.create_table(
        "document_versions",
        sa.Column("document_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("storage_key", sa.String(length=400), nullable=True),
        sa.Column("etag", sa.String(length=200), nullable=True),
        sa.Column("last_modified", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_versions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_versions")),
        sa.UniqueConstraint("document_id", "sha256", name="uq_document_versions_document_sha256"),
    )
    op.create_index(
        op.f("ix_document_versions_created_at"), "document_versions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_document_versions_document_id_version",
        "document_versions",
        ["document_id", "version"],
        unique=False,
    )

    op.create_table(
        "ingestion_errors",
        sa.Column("job_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("source_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("source_run_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column(
            "context",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_jobs.id"],
            name=op.f("fk_ingestion_errors_job_id_ingestion_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["municipality_sources.id"],
            name=op.f("fk_ingestion_errors_source_id_municipality_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["source_runs.id"],
            name=op.f("fk_ingestion_errors_source_run_id_source_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_errors")),
    )
    op.create_index(
        op.f("ix_ingestion_errors_created_at"), "ingestion_errors", ["created_at"], unique=False
    )
    op.create_index(
        "ix_ingestion_errors_job_id_created_at",
        "ingestion_errors",
        ["job_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_errors_source_id_stage",
        "ingestion_errors",
        ["source_id", "stage"],
        unique=False,
    )

    op.create_table(
        "opportunity_versions",
        sa.Column("opportunity_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "snapshot",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "changed_fields",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("source_run_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["procurement_opportunities.id"],
            name=op.f("fk_opportunity_versions_opportunity_id_procurement_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"],
            ["source_runs.id"],
            name=op.f("fk_opportunity_versions_source_run_id_source_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_versions")),
        sa.UniqueConstraint("opportunity_id", "version", name="uq_opportunity_versions_version"),
    )
    op.create_index(
        op.f("ix_opportunity_versions_created_at"),
        "opportunity_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_versions_opportunity_created",
        "opportunity_versions",
        ["opportunity_id", "created_at"],
        unique=False,
    )

    op.create_table(
        "document_text",
        sa.Column("document_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("document_version_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("extraction_method", sa.String(length=24), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "structure",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("ocr_used", sa.Boolean(), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_text_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_version_id"],
            ["document_versions.id"],
            name=op.f("fk_document_text_document_version_id_document_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_text")),
        sa.UniqueConstraint("document_id", name="uq_document_text_document_id"),
    )
    op.create_index(
        op.f("ix_document_text_created_at"), "document_text", ["created_at"], unique=False
    )
    op.create_index(
        "ix_document_text_extraction_method", "document_text", ["extraction_method"], unique=False
    )

    op.create_table(
        "opportunity_events",
        sa.Column("opportunity_id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("version_id", app.db.base_class.GUID(length=36), nullable=True),
        sa.Column("field", sa.String(length=80), nullable=True),
        sa.Column(
            "previous_value",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "new_value",
            postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", app.db.base_class.GUID(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["procurement_opportunities.id"],
            name=op.f("fk_opportunity_events_opportunity_id_procurement_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["opportunity_versions.id"],
            name=op.f("fk_opportunity_events_version_id_opportunity_versions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_events")),
    )
    op.create_index(
        op.f("ix_opportunity_events_created_at"), "opportunity_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunity_events_occurred_at"),
        "opportunity_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_events_opportunity_occurred",
        "opportunity_events",
        ["opportunity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_opportunity_events_type_occurred",
        "opportunity_events",
        ["event_type", "occurred_at"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_opportunity_events_type_occurred", table_name="opportunity_events")
    op.drop_index("ix_opportunity_events_opportunity_occurred", table_name="opportunity_events")
    op.drop_index(op.f("ix_opportunity_events_occurred_at"), table_name="opportunity_events")
    op.drop_index(op.f("ix_opportunity_events_created_at"), table_name="opportunity_events")

    op.drop_table("opportunity_events")
    op.drop_index("ix_document_text_extraction_method", table_name="document_text")
    op.drop_index(op.f("ix_document_text_created_at"), table_name="document_text")

    op.drop_table("document_text")
    op.drop_index("ix_opportunity_versions_opportunity_created", table_name="opportunity_versions")
    op.drop_index(op.f("ix_opportunity_versions_created_at"), table_name="opportunity_versions")

    op.drop_table("opportunity_versions")
    op.drop_index("ix_ingestion_errors_source_id_stage", table_name="ingestion_errors")
    op.drop_index("ix_ingestion_errors_job_id_created_at", table_name="ingestion_errors")
    op.drop_index(op.f("ix_ingestion_errors_created_at"), table_name="ingestion_errors")

    op.drop_table("ingestion_errors")
    op.drop_index("ix_document_versions_document_id_version", table_name="document_versions")
    op.drop_index(op.f("ix_document_versions_created_at"), table_name="document_versions")

    op.drop_table("document_versions")
    op.drop_index("ix_source_runs_source_id_started_at", table_name="source_runs")
    op.drop_index(op.f("ix_source_runs_job_id"), table_name="source_runs")
    op.drop_index(op.f("ix_source_runs_created_at"), table_name="source_runs")

    op.drop_table("source_runs")
    op.drop_index(op.f("ix_opportunity_categories_created_at"), table_name="opportunity_categories")
    op.drop_index("ix_opportunity_categories_category_id", table_name="opportunity_categories")

    op.drop_table("opportunity_categories")
    op.drop_index("ix_documents_sha256", table_name="documents")
    op.drop_index("ix_documents_opportunity_id_created", table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")

    op.drop_table("documents")
    op.drop_index(
        op.f("ix_procurement_opportunities_status"), table_name="procurement_opportunities"
    )
    op.drop_index(
        op.f("ix_procurement_opportunities_reference_number"),
        table_name="procurement_opportunities",
    )
    op.drop_index(
        op.f("ix_procurement_opportunities_created_at"), table_name="procurement_opportunities"
    )
    op.drop_index("ix_opportunities_status_closing_at", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_source_last_seen", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_published_at", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_province_status", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_procurement_type", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_municipality_status", table_name="procurement_opportunities")
    op.drop_index("ix_opportunities_content_hash", table_name="procurement_opportunities")

    op.drop_table("procurement_opportunities")
    op.drop_index("ix_ingestion_jobs_status_scheduled_for", table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_source_id_created_at", table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_queue_job_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_created_at"), table_name="ingestion_jobs")

    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_municipality_sources_source_type"), table_name="municipality_sources")
    op.drop_index(op.f("ix_municipality_sources_province_id"), table_name="municipality_sources")
    op.drop_index(op.f("ix_municipality_sources_name"), table_name="municipality_sources")
    op.drop_index(
        op.f("ix_municipality_sources_municipality_id"), table_name="municipality_sources"
    )
    op.drop_index("ix_municipality_sources_health_status", table_name="municipality_sources")
    op.drop_index(op.f("ix_municipality_sources_created_at"), table_name="municipality_sources")
    op.drop_index("ix_municipality_sources_active_priority", table_name="municipality_sources")
    op.drop_index(op.f("ix_municipality_sources_active"), table_name="municipality_sources")

    op.drop_table("municipality_sources")
    op.drop_index(op.f("ix_municipalities_slug"), table_name="municipalities")
    op.drop_index("ix_municipalities_province_id_type", table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_province_id"), table_name="municipalities")
    op.drop_index("ix_municipalities_name_lower", table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_name"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_district_id"), table_name="municipalities")
    op.drop_index(op.f("ix_municipalities_created_at"), table_name="municipalities")

    op.drop_table("municipalities")
    op.drop_index(op.f("ix_districts_slug"), table_name="districts")
    op.drop_index("ix_districts_province_id_name", table_name="districts")
    op.drop_index(op.f("ix_districts_province_id"), table_name="districts")
    op.drop_index(op.f("ix_districts_name"), table_name="districts")
    op.drop_index(op.f("ix_districts_created_at"), table_name="districts")

    op.drop_table("districts")
    op.drop_index(op.f("ix_source_connectors_key"), table_name="source_connectors")
    op.drop_index(op.f("ix_source_connectors_created_at"), table_name="source_connectors")

    op.drop_table("source_connectors")
    op.drop_index(op.f("ix_provinces_slug"), table_name="provinces")
    op.drop_index(op.f("ix_provinces_name"), table_name="provinces")
    op.drop_index(op.f("ix_provinces_created_at"), table_name="provinces")

    op.drop_table("provinces")
    op.drop_index("ix_contacts_email", table_name="contacts")
    op.drop_index(op.f("ix_contacts_created_at"), table_name="contacts")

    op.drop_table("contacts")
    op.drop_index("ix_categories_parent_id_name", table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories")

    op.drop_table("categories")
    # ### end Alembic commands ###
